/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bedroom.glb -o src/scene/RoomGLB.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import type { GLTF } from 'three-stdlib'
import InteractiveObject from '../interaction/InteractiveObject'
import { applyPbrMaps } from '../materials/pbrTextures'
import { polishSceneMaterials, setLampGlow } from '../materials/livingMaterials'
import { AmbientMotion } from './AmbientMotion'
import { usePortfolioStore } from '../state/usePortfolioStore'

type GLTFResult = GLTF & {
  nodes: {
    GA_cactus: THREE.Mesh
    GA_clay_pot: THREE.Mesh
    GA_ground_pot: THREE.Mesh
    GA_stones: THREE.Mesh
    GA_vase: THREE.Mesh
    GA_cactus001: THREE.Mesh
    GA_clay_pot001: THREE.Mesh
    GA_ground_pot001: THREE.Mesh
    GA_stones001: THREE.Mesh
    GA_vase001: THREE.Mesh
    GA_cactus002: THREE.Mesh
    GA_clay_pot002: THREE.Mesh
    GA_ground_pot002: THREE.Mesh
    GA_stones002: THREE.Mesh
    ['706090']: THREE.Mesh
    bed: THREE.Mesh
    bed001: THREE.Mesh
    bed002: THREE.Mesh
    bed003: THREE.Mesh
    chairCombinedhighPoly: THREE.Mesh
    Circle: THREE.Mesh
    Circle001: THREE.Mesh
    Circle002: THREE.Mesh
    Circle003: THREE.Mesh
    Circle004: THREE.Mesh
    Circle005: THREE.Mesh
    Circle006: THREE.Mesh
    Circle007: THREE.Mesh
    Circle009: THREE.Mesh
    Circle009_1: THREE.Mesh
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube034_1: THREE.Mesh
    Cube034_2: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube014_1: THREE.Mesh
    Cube014_2: THREE.Mesh
    Cube015_1: THREE.Mesh
    Cube015_2: THREE.Mesh
    Cube016_1: THREE.Mesh
    Cube016_2: THREE.Mesh
    Cube015: THREE.Mesh
    Cube018_1: THREE.Mesh
    Cube018_2: THREE.Mesh
    Cube019_1: THREE.Mesh
    Cube019_2: THREE.Mesh
    Cube020_1: THREE.Mesh
    Cube020_2: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube022: THREE.Mesh
    Cube023: THREE.Mesh
    Cube024: THREE.Mesh
    Cube025: THREE.Mesh
    Cube038: THREE.Mesh
    Cube038_1: THREE.Mesh
    Cube027: THREE.Mesh
    Cube028: THREE.Mesh
    Cube029: THREE.Mesh
    Cube030: THREE.Mesh
    Cube011_1: THREE.Mesh
    Cube011_2: THREE.Mesh
    Cube032: THREE.Mesh
    Cube039: THREE.Mesh
    Cube039_1: THREE.Mesh
    Cube040: THREE.Mesh
    Cube040_1: THREE.Mesh
    Cube041: THREE.Mesh
    Cube041_1: THREE.Mesh
    Cube036: THREE.Mesh
    Cube004_1: THREE.Mesh
    Cube004_2: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube005_2: THREE.Mesh
    Cube023_1: THREE.Mesh
    Cube023_2: THREE.Mesh
    Cube024_1: THREE.Mesh
    Cube024_2: THREE.Mesh
    Cube025_1: THREE.Mesh
    Cube025_2: THREE.Mesh
    Cube027_1: THREE.Mesh
    Cube027_2: THREE.Mesh
    Cube028_1: THREE.Mesh
    Cube028_2: THREE.Mesh
    Cube067: THREE.Mesh
    Cube069_1: THREE.Mesh
    Cube069_2: THREE.Mesh
    Cube069: THREE.Mesh
    Cube071_1: THREE.Mesh
    Cube071_2: THREE.Mesh
    Cube071: THREE.Mesh
    Cube073_1: THREE.Mesh
    Cube073_2: THREE.Mesh
    Cube074_1: THREE.Mesh
    Cube074_2: THREE.Mesh
    Cube075_1: THREE.Mesh
    Cube075_2: THREE.Mesh
    Cube075: THREE.Mesh
    Cube077_1: THREE.Mesh
    Cube077_2: THREE.Mesh
    Cube078_1: THREE.Mesh
    Cube078_2: THREE.Mesh
    Cube079_1: THREE.Mesh
    Cube079_2: THREE.Mesh
    Cube079: THREE.Mesh
    Cube081_1: THREE.Mesh
    Cube081_2: THREE.Mesh
    Cube081: THREE.Mesh
    Cube082: THREE.Mesh
    Cube084_1: THREE.Mesh
    Cube084_2: THREE.Mesh
    Cube085_1: THREE.Mesh
    Cube085_2: THREE.Mesh
    Cube086_1: THREE.Mesh
    Cube086_2: THREE.Mesh
    Cube087_1: THREE.Mesh
    Cube087_2: THREE.Mesh
    Cube088_1: THREE.Mesh
    Cube088_2: THREE.Mesh
    Cube089_1: THREE.Mesh
    Cube089_2: THREE.Mesh
    Cube091_1: THREE.Mesh
    Cube091_2: THREE.Mesh
    Cube092_1: THREE.Mesh
    Cube092_2: THREE.Mesh
    Cube093_1: THREE.Mesh
    Cube093_2: THREE.Mesh
    Cube092: THREE.Mesh
    Cube093: THREE.Mesh
    Cube094: THREE.Mesh
    Cube095: THREE.Mesh
    Cube096: THREE.Mesh
    Cube097: THREE.Mesh
    Cube098: THREE.Mesh
    Cube099: THREE.Mesh
    Cube100: THREE.Mesh
    Cube101: THREE.Mesh
    Cube102: THREE.Mesh
    Cube103: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Mesh014: THREE.Mesh
    Mesh014_1: THREE.Mesh
    Mesh014_2: THREE.Mesh
    Mesh014_3: THREE.Mesh
    Mesh014_4: THREE.Mesh
    Mesh014_5: THREE.Mesh
    Mesh014_6: THREE.Mesh
    Mesh014_7: THREE.Mesh
    Mesh014_8: THREE.Mesh
    Mesh014_9: THREE.Mesh
    Mesh014_10: THREE.Mesh
    Mesh014_11: THREE.Mesh
    headphone: THREE.Mesh
    Icosphere_1: THREE.Mesh
    Icosphere_2: THREE.Mesh
    Icosphere021: THREE.Mesh
    Icosphere021_1: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Cylinder001_2: THREE.Mesh
    Cylinder001_3: THREE.Mesh
    Cylinder001_4: THREE.Mesh
    Plane: THREE.Mesh
    Plane013_1: THREE.Mesh
    Plane013_2: THREE.Mesh
    Plane013_3: THREE.Mesh
    Plane019: THREE.Mesh
    Plane019_1: THREE.Mesh
    Plane019_2: THREE.Mesh
    Plane019_3: THREE.Mesh
    Plane019_4: THREE.Mesh
    Plane019_5: THREE.Mesh
    Plane019_6: THREE.Mesh
    Plane152: THREE.Mesh
    Plane154_1: THREE.Mesh
    Plane154_2: THREE.Mesh
    Plane155_1: THREE.Mesh
    Plane155_2: THREE.Mesh
    Plane156_1: THREE.Mesh
    Plane156_2: THREE.Mesh
    Plane156: THREE.Mesh
    Plane157: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder005_1: THREE.Mesh
    Cylinder005_2: THREE.Mesh
    speaker: THREE.Mesh
    speaker001: THREE.Mesh
    Sphere005_1: THREE.Mesh
    Sphere005_2: THREE.Mesh
    Text001: THREE.Mesh
    Text002: THREE.Mesh
    uploads_files_1979612_cardboar_box_pack: THREE.Mesh
    uploads_files_1979612_cardboar_box_pack001: THREE.Mesh
    uploads_files_1979612_cardboar_box_pack002: THREE.Mesh
    uploads_files_1979612_cardboar_box_pack004: THREE.Mesh
    uploads_files_1979612_cardboar_box_pack005: THREE.Mesh
  }
  materials: {
    cactus_gasteria: THREE.MeshStandardMaterial
    clay_pot: THREE.MeshStandardMaterial
    ground_pot5: THREE.MeshStandardMaterial
    stones: THREE.MeshStandardMaterial
    vase_gasteria: THREE.MeshStandardMaterial
    ['black mouse']: THREE.MeshStandardMaterial
    wall: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    room_old_house_MSH8_takht_room_obj_pasted__lambert5: THREE.MeshStandardMaterial
    bed: THREE.MeshStandardMaterial
    ['ofis_cher.002']: THREE.MeshStandardMaterial
    grey: THREE.MeshStandardMaterial
    ['red.002']: THREE.MeshPhysicalMaterial
    b_pvc: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    brown: THREE.MeshStandardMaterial
    floor: THREE.MeshStandardMaterial
    ['wood table']: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
    ['choti table']: THREE.MeshStandardMaterial
    pic: THREE.MeshStandardMaterial
    ['pic ']: THREE.MeshStandardMaterial
    ['pic 1']: THREE.MeshStandardMaterial
    pics: THREE.MeshStandardMaterial
    picc: THREE.MeshStandardMaterial
    piic: THREE.MeshStandardMaterial
    blue: THREE.MeshStandardMaterial
    ['red.001']: THREE.MeshStandardMaterial
    flower: THREE.MeshStandardMaterial
    flowerr: THREE.MeshStandardMaterial
    ['white computer']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    bread: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
    ['eye back.001']: THREE.MeshStandardMaterial
    redd: THREE.MeshStandardMaterial
    turquip: THREE.MeshStandardMaterial
    ['dark blue']: THREE.MeshStandardMaterial
    cardboard: THREE.MeshStandardMaterial
    ['cardboard.001']: THREE.MeshStandardMaterial
    fridge: THREE.MeshStandardMaterial
    ['broewn riug']: THREE.MeshPhysicalMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['grey metallic']: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshPhysicalMaterial
    ['Lid Metal']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_14']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_03']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_04']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_14.001']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_16']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_07']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_08']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_09']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_10']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_11']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_12']: THREE.MeshStandardMaterial
    ['DB_Apps&Tech_101_13']: THREE.MeshStandardMaterial
    bulb: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Metal Cover']: THREE.MeshStandardMaterial
    Label: THREE.MeshStandardMaterial
    Fill: THREE.MeshStandardMaterial
    moniter: THREE.MeshStandardMaterial
    ['eye back.002']: THREE.MeshStandardMaterial
    wire_029029029: THREE.MeshStandardMaterial
    ['file.001']: THREE.MeshStandardMaterial
    filee: THREE.MeshStandardMaterial
    file: THREE.MeshStandardMaterial
    ['rug f']: THREE.MeshStandardMaterial
    ['new ruug']: THREE.MeshStandardMaterial
    rug: THREE.MeshStandardMaterial
    ['rug.001']: THREE.MeshStandardMaterial
    rugg: THREE.MeshStandardMaterial
    metallic_k: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['eye back']: THREE.MeshStandardMaterial
    lamp: THREE.MeshStandardMaterial
    ['neechy lamp']: THREE.MeshStandardMaterial
    ['cardboard.002']: THREE.MeshStandardMaterial
  }
}

const PALETTE = {
  sage: '#7A8667',
  mutedOlive: '#737B61',
  terracotta: '#C98268',
  dustyPeach: '#D99A7C',
  warmCream: '#D7D0B8',
  warmCream2: '#D7D0C2',
  warmCream3: '#CEC7BA',
  darkWood: '#5A3824',
  warmWood: '#80502F',
  pot1: '#A9684D',
  pot2: '#B87558',
  pot3: '#CFC6B3',
  pot4: '#737B61',
  mutedTerracotta: '#A9603F',
  mutedBurgundy: '#6E2727',
  sageBacking: '#66735A',
  navy: '#34465F',
  charcoal: '#3B3028',
  lampShade: '#D8CBB8',
} as const

function tintClone(source: THREE.Material, hex: string) {
  const cloned = source.clone() as THREE.MeshStandardMaterial
  if (cloned.color) {
    cloned.color.set(hex)
  }
  cloned.needsUpdate = true
  return cloned
}

function chairUpholsteryGeometry(source: THREE.BufferGeometry) {
  const geometry = source.clone()
  const position = geometry.getAttribute('position')
  const colors = new Float32Array(position.count * 3)
  const fabric = new THREE.Color(PALETTE.mutedOlive)
  const metal = new THREE.Color('#c8c4bc')

  // Combined chair mesh: seat/back are the upper local-Y region.
  // Keep the pedestal, arms hardware and wheel cluster on a light metal value.
  for (let i = 0; i < position.count; i++) {
    const c = position.getY(i) >= 0.22 ? fabric : metal
    colors[i * 3] = c.r
    colors[i * 3 + 1] = c.g
    colors[i * 3 + 2] = c.b
  }

  geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3))
  return geometry
}

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/models/bedroom.glb') as unknown as GLTFResult
  const lampOn = usePortfolioStore((state) => state.lampOn)

  const coloured = React.useMemo(() => {
    const duvetSource = (nodes.Cube008.material as THREE.Material) || materials.white
    const mattressSource = (nodes.Cube007.material as THREE.Material) || materials.white

    const chairMat = tintClone(materials['ofis_cher.002'], '#ffffff')
    chairMat.vertexColors = true
    chairMat.roughness = 0.82
    chairMat.metalness = 0.04
    chairMat.envMapIntensity = 0.25

    const result = {
      beddingSage: tintClone(duvetSource, PALETTE.sage),
      beddingTerracotta: tintClone(materials.bed, PALETTE.dustyPeach),
      beddingSheet: tintClone(materials.room_old_house_MSH8_takht_room_obj_pasted__lambert5, PALETTE.warmCream),
      beddingMattress: tintClone(mattressSource, PALETTE.warmCream2),
      beddingPillow1: tintClone(materials['Material.005'], PALETTE.warmCream),
      beddingPillow2: tintClone(materials.wall, PALETTE.sage),
      chair: chairMat,
      chairGeometry: chairUpholsteryGeometry(nodes.chairCombinedhighPoly.geometry),
      cabinet: tintClone(materials['choti table'], PALETTE.warmCream2),
      foregroundCabinet: tintClone(materials.fridge, PALETTE.warmCream3),
      stool: tintClone(materials['choti table'], PALETTE.mutedTerracotta),
      deskSurface: tintClone(materials['wood table'], PALETTE.warmCream2),
      pot1: tintClone(materials.clay_pot, PALETTE.pot1),
      pot2: tintClone(materials.ground_pot5, PALETTE.pot2),
      pot3: tintClone(materials.vase_gasteria, PALETTE.pot3),
      pot4: tintClone(materials.clay_pot, PALETTE.pot4),
      accentSage: tintClone(materials.green, PALETTE.sage),
      accentTerracotta: tintClone(materials['red.001'], PALETTE.mutedTerracotta),
      accentNavy: tintClone(materials.blue, PALETTE.navy),
      accentCream: tintClone(materials.white, PALETTE.warmCream2),
      accentBurgundy: tintClone(materials['red.002'], PALETTE.mutedBurgundy),
      accentWood: tintClone(materials.brown, PALETTE.warmWood),
      accentDarkWood: tintClone(materials.brown, PALETTE.darkWood),
      lampStand: tintClone(materials['neechy lamp'], PALETTE.charcoal),
      shelfBacking: tintClone(materials['dark blue'], PALETTE.sageBacking),
      shelfAccent: tintClone(materials['dark blue'], PALETTE.mutedOlive),
      largeCabinetMat: tintClone(materials['choti table'], PALETTE.warmCream3),
      stoolSeat: tintClone(materials['choti table'], PALETTE.mutedTerracotta),
      rightStorageBody: tintClone(materials['Material.003'], PALETTE.mutedOlive),
      lampShadeMat: tintClone(materials['Material.006'], PALETTE.lampShade),
      floorLampShade: tintClone(materials.lamp, PALETTE.lampShade),
      standDark: tintClone(materials['Material.001'], PALETTE.darkWood),
      standOlive: tintClone(materials['Material.004'], PALETTE.mutedOlive),
      shelfFrameMat: tintClone(materials.white, PALETTE.warmCream2),
      accWhiteToSage: tintClone(materials.white, PALETTE.sage),
      accWhiteToNavy: tintClone(materials.white, PALETTE.navy),
      accWhiteToTerracotta: tintClone(materials.white, PALETTE.mutedTerracotta),
      accWhiteToCream: tintClone(materials.white, PALETTE.warmCream2),
      deskAccent: tintClone(materials.blue, PALETTE.navy),
      cactusMat: tintClone(materials.cactus_gasteria, PALETTE.sage),
      stonesMat: tintClone(materials.stones, PALETTE.warmCream3),
    }

    // The source GLB is largely untextured. Apply tileable PBR map sets by material role
    // so the scene responds to the cinematic lighting with grain, weave, micro-roughness,
    // and subtle relief instead of flat colour blocks.
    applyPbrMaps(materials.wall, 'plaster', 1.5)
    applyPbrMaps(materials.floor, 'plaster', 2)
    applyPbrMaps(materials.brown, 'wood', 2.8)
    applyPbrMaps(materials['wood table'], 'wood', 2.1)
    applyPbrMaps(materials['choti table'], 'wood', 1.8)
    applyPbrMaps(result.accentWood, 'wood', 2.4)
    applyPbrMaps(result.accentDarkWood, 'wood', 2.4)
    applyPbrMaps(result.deskSurface, 'wood', 2.1)
    ;[result.beddingSage, result.beddingTerracotta, result.beddingSheet, result.beddingMattress, result.beddingPillow1, result.beddingPillow2].forEach((material) => applyPbrMaps(material, 'linen', 4.5))
    ;[result.pot1, result.pot2, result.pot3, result.pot4, result.stonesMat, result.lampShadeMat, result.floorLampShade].forEach((material) => applyPbrMaps(material, 'ceramic', 1.4))
    ;[materials['grey metallic'], materials['Lid Metal'], materials['Metal Cover'], materials.metallic_k, result.lampStand].forEach((material) => applyPbrMaps(material, 'metal', 2))
    polishSceneMaterials(materials)

    if (typeof window !== 'undefined') {
      (window as any).__bedroomColours = {
        sage: '#' + result.beddingSage.color.getHexString(),
        terracotta: '#' + result.beddingTerracotta.color.getHexString(),
        sheet: '#' + result.beddingSheet.color.getHexString(),
        mattress: '#' + result.beddingMattress.color.getHexString(),
        cabinet: '#' + result.cabinet.color.getHexString(),
        stool: '#' + result.stool.color.getHexString(),
        pot1: '#' + result.pot1.color.getHexString(),
        chairMetalness: result.chair.metalness,
        chairVertexColors: result.chair.vertexColors,
        cube008Name: duvetSource?.name,
      }
    }

    return result
  }, [nodes, materials])

  React.useEffect(() => {
    Object.values(nodes).forEach((node) => {
      if ((node as THREE.Mesh).isMesh) {
        node.castShadow = true;
        node.receiveShadow = true;
      }
    });
  }, [nodes]);

  useFrame((_, delta) => {
    setLampGlow([
      materials.lamp,
      materials['Material.006'],
      coloured.floorLampShade,
      coloured.lampShadeMat,
    ], lampOn, delta)
    const monitor = materials.moniter
    if (monitor) {
      const pulse = 0.82 + Math.sin(performance.now() * 0.0016) * 0.08
      monitor.emissiveIntensity = THREE.MathUtils.damp(monitor.emissiveIntensity, pulse, 2.4, delta)
    }
  })

  return (
    <group {...props} dispose={null}>
      <InteractiveObject id="PLANT">
        <AmbientMotion amount={0.01} speed={0.38}>
        <group position={[0.838, -0.861, -2.358]} rotation={[Math.PI / 2, 0, 0]} scale={0.026}>
          <mesh geometry={nodes.GA_cactus.geometry} material={coloured.cactusMat} />
          <mesh geometry={nodes.GA_clay_pot.geometry} material={coloured.pot3} />
          <mesh geometry={nodes.GA_ground_pot.geometry} material={coloured.pot3} />
          <mesh geometry={nodes.GA_stones.geometry} material={coloured.stonesMat} />
          <mesh geometry={nodes.GA_vase.geometry} material={coloured.pot2} />
        </group>
        <group position={[-0.81, -0.861, -2.358]} rotation={[Math.PI / 2, 0, 0]} scale={0.026}>
          <mesh geometry={nodes.GA_cactus001.geometry} material={coloured.cactusMat} />
          <mesh geometry={nodes.GA_clay_pot001.geometry} material={coloured.pot3} />
          <mesh geometry={nodes.GA_ground_pot001.geometry} material={coloured.pot3} />
          <mesh geometry={nodes.GA_stones001.geometry} material={coloured.stonesMat} />
          <mesh geometry={nodes.GA_vase001.geometry} material={coloured.pot4} />
        </group>
        <group position={[0.019, -0.878, -2.358]} rotation={[Math.PI / 2, 0, 0]} scale={0.026}>
          <mesh geometry={nodes.GA_cactus002.geometry} material={coloured.cactusMat} />
          <mesh geometry={nodes.GA_clay_pot002.geometry} material={coloured.pot1} />
          <mesh geometry={nodes.GA_ground_pot002.geometry} material={coloured.pot3} />
          <mesh geometry={nodes.GA_stones002.geometry} material={coloured.stonesMat} />
        </group>
        </AmbientMotion>
      </InteractiveObject>
      <mesh geometry={nodes['706090'].geometry} material={materials['black mouse']} position={[-2.179, -0.662, 0.285]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.03} />
      <InteractiveObject id="BED">
        <mesh geometry={nodes.bed.geometry} material={coloured.beddingPillow2} position={[-1.043, -1.58, 1.83]} rotation={[Math.PI / 2, 0, 0]} scale={[0.384, 0.348, 0.348]} />
        <mesh geometry={nodes.bed001.geometry} material={coloured.beddingPillow1} position={[-1.043, -1.58, 1.83]} rotation={[Math.PI / 2, 0, 0]} scale={[0.384, 0.348, 0.348]} />
        <mesh geometry={nodes.bed002.geometry} material={coloured.beddingSheet} position={[-1.043, -1.58, 1.83]} rotation={[Math.PI / 2, 0, 0]} scale={[0.384, 0.348, 0.348]} />
        <mesh geometry={nodes.bed003.geometry} material={coloured.beddingTerracotta} position={[-1.043, -1.58, 1.83]} rotation={[Math.PI / 2, 0, 0]} scale={[0.384, 0.348, 0.348]} />
        <mesh geometry={nodes.Cube007.geometry} material={coloured.beddingMattress} position={[-1.051, -1.834, 1.907]} scale={[1.628, 0.114, 0.586]} />
        <mesh geometry={nodes.Cube008.geometry} material={coloured.beddingSage} position={[-1.051, -1.493, 1.907]} scale={[1.638, 0.115, 0.589]} />
      </InteractiveObject>
      <InteractiveObject id="DESK">
        <mesh geometry={coloured.chairGeometry} material={coloured.chair} position={[-1.39, -1.953, -0.394]} rotation={[0, -Math.PI / 2, 0]} scale={1.752} />
      </InteractiveObject>
      <mesh geometry={nodes.Circle.geometry} material={materials.grey} position={[-2.179, -0.712, 0.285]} scale={0.226} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['black mouse']} position={[3.279, -0.996, -2.586]} scale={0.087} />
      <mesh geometry={nodes.Circle002.geometry} material={materials['black mouse']} position={[3.279, -0.65, -2.586]} scale={0.087} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['black mouse']} position={[3.279, -0.31, -2.586]} scale={0.087} />
      <mesh geometry={nodes.Circle004.geometry} material={materials['black mouse']} position={[3.279, 0.035, -2.586]} scale={0.087} />
      <mesh geometry={nodes.Circle005.geometry} material={materials['black mouse']} position={[3.279, 0.416, -2.586]} scale={0.087} />
      <mesh geometry={nodes.Circle006.geometry} material={materials['black mouse']} position={[3.279, 0.761, -2.586]} scale={0.087} />
      <mesh geometry={nodes.Circle007.geometry} material={materials['black mouse']} position={[3.279, 1.101, -2.586]} scale={0.087} />
      <group position={[0.186, -1.95, -0.344]} scale={1.173}>
        <mesh geometry={nodes.Circle009.geometry} material={coloured.accentBurgundy} />
        <mesh geometry={nodes.Circle009_1.geometry} material={materials.b_pvc} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} scale={[2.781, 1.95, 2.67]} />
      <mesh geometry={nodes.Cube001.geometry} material={coloured.accentDarkWood} position={[-2.429, -1.329, -2.225]} scale={[0.348, 0.611, 0.441]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.floor} scale={[2.781, 1.95, 2.67]} />
      <InteractiveObject id="DESK">
        <mesh geometry={nodes.Cube003.geometry} material={coloured.deskSurface} position={[-2.335, -0.754, -0.385]} scale={[0.45, 0.044, 1.32]} />
      </InteractiveObject>
      <mesh geometry={nodes.Cube004.geometry} material={materials.wall} position={[-2.429, -1.659, -2.225]} scale={[0.348, 0.241, 0.378]} />
      <group position={[-2.283, -1.312, -2.128]} scale={[0.199, 0.108, 0.275]}>
        <mesh geometry={nodes.Cube034_1.geometry} material={materials.grey} />
        <mesh geometry={nodes.Cube034_2.geometry} material={coloured.accWhiteToCream} />
      </group>
      <mesh geometry={nodes.Cube006.geometry} material={coloured.largeCabinetMat} position={[1.583, -1.224, 1.93]} scale={[0.804, 0.729, 0.586]} />
      <mesh geometry={nodes.Cube010.geometry} material={coloured.stoolSeat} position={[1.39, -1.777, -0.994]} rotation={[-Math.PI / 2, 0, -1.412]} scale={[0.303, 0.016, 0.172]} />
      <mesh geometry={nodes.Cube011.geometry} material={coloured.accWhiteToCream} position={[2.428, -0.056, -2.666]} scale={[0.128, 0.128, 0.007]} />
      <group position={[2.284, 0.782, -2.663]} rotation={[Math.PI / 2, -1.554, 0]} scale={[0.327, 0.014, 0.392]}>
        <mesh geometry={nodes.Cube014_1.geometry} material={materials.brown} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials.pic} />
      </group>
      <group position={[1.284, 0.935, -2.663]} rotation={[-Math.PI / 2, -0.017, Math.PI]} scale={[0.534, 0.021, 0.355]}>
        <mesh geometry={nodes.Cube015_1.geometry} material={materials.brown} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials['pic ']} />
      </group>
      <group position={[-2.097, 0.782, -2.665]} rotation={[-Math.PI / 2, -0.017, Math.PI]} scale={[0.482, 0.01, 0.32]}>
        <mesh geometry={nodes.Cube016_1.geometry} material={materials.brown} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials['pic 1']} />
      </group>
      <mesh geometry={nodes.Cube015.geometry} material={materials.brown} position={[-2.635, 1.092, -0.576]} scale={[0.253, 0.057, 1.729]} />
      <group position={[-2.78, 0.36, -1.747]} rotation={[-1.554, 0, -Math.PI / 2]} scale={[0.496, 0.013, 0.394]}>
        <mesh geometry={nodes.Cube018_1.geometry} material={materials.brown} />
        <mesh geometry={nodes.Cube018_2.geometry} material={materials.pics} />
      </group>
      <group position={[-2.78, 0.547, -0.657]} rotation={[1.588, 0, -Math.PI / 2]} scale={[0.417, 0.009, 0.294]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials.brown} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials.picc} />
      </group>
      <group position={[-2.78, 0.589, 0.196]} rotation={[1.588, 0, -Math.PI / 2]} scale={[0.33, 0.007, 0.233]}>
        <mesh geometry={nodes.Cube020_1.geometry} material={materials.brown} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials.piic} />
      </group>
      <mesh geometry={nodes.Cube019.geometry} material={materials.brown} position={[-2.604, 0.776, 1.577]} scale={[0.186, 0.036, 0.36]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials.brown} position={[-2.604, 0.501, 2.292]} scale={[0.186, 0.036, 0.261]} />
      <mesh geometry={nodes.Cube022.geometry} material={coloured.deskAccent} position={[-2.216, -1.167, -2.034]} scale={[0.129, 0.039, 0.178]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials.brown} position={[-2.67, 1.285, -1.737]} scale={[0.113, 0.137, 0.065]} />
      <mesh geometry={nodes.Cube024.geometry} material={coloured.accentWood} position={[1.144, -1.437, -2.306]} rotation={[0, 0, -Math.PI / 2]} scale={[0.512, 0.031, 0.364]} />
      <mesh geometry={nodes.Cube025.geometry} material={coloured.accentTerracotta} position={[-2.67, 1.312, -1.846]} scale={[0.113, 0.162, 0.04]} />
      <group position={[-2.67, 1.297, -1.924]} scale={[0.113, 0.147, 0.027]}>
        <mesh geometry={nodes.Cube038.geometry} material={coloured.accWhiteToCream} />
        <mesh geometry={nodes.Cube038_1.geometry} material={materials['red.002']} />
      </group>
      <mesh geometry={nodes.Cube027.geometry} material={materials['black mouse']} position={[1.536, -1.93, -2.294]} scale={[0.152, 0.016, 0.133]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials.flower} position={[1.535, 0.422, -2.294]} scale={[0.198, 0.179, 0.198]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['black mouse']} position={[0.441, 1.761, -2.623]} scale={0.061} />
      <mesh geometry={nodes.Cube030.geometry} material={materials.flowerr} position={[0.442, 1.046, -1.038]} scale={[0.186, 0.122, 0.186]} />
      <InteractiveObject id="LAPTOP">
        <group position={[-2.59, -0.117, -0.351]} scale={[0.024, 0.432, 0.714]}>
          <mesh geometry={nodes.Cube011_1.geometry} material={materials['white computer']} />
          <mesh geometry={nodes.Cube011_2.geometry} material={materials.b_pvc} />
        </group>
      </InteractiveObject>
      <mesh geometry={nodes.Cube032.geometry} material={coloured.rightStorageBody} position={[2.305, -1.394, -2.357]} scale={[0.337, 0.558, 0.32]} />
      <group position={[-2.67, 1.345, -1.987]} scale={[0.113, 0.198, 0.031]}>
        <mesh geometry={nodes.Cube039.geometry} material={materials.brown} />
        <mesh geometry={nodes.Cube039_1.geometry} material={materials.white} />
      </group>
      <group position={[-2.67, 1.285, -2.072]} scale={[0.113, 0.137, 0.044]}>
        <mesh geometry={nodes.Cube040.geometry} material={coloured.accWhiteToCream} />
        <mesh geometry={nodes.Cube040_1.geometry} material={materials.bread} />
      </group>
      <group position={[-2.67, 1.312, -2.147]} scale={[0.113, 0.162, 0.029]}>
        <mesh geometry={nodes.Cube041.geometry} material={coloured.accWhiteToCream} />
        <mesh geometry={nodes.Cube041_1.geometry} material={materials.green} />
      </group>
      <mesh geometry={nodes.Cube036.geometry} material={materials['eye back.001']} position={[1.38, -0.03, 1.835]} rotation={[Math.PI, 0, Math.PI]} scale={[0.019, 0.34, 0.562]} />
      <group position={[-2.67, 1.285, -1.232]} scale={[0.113, 0.137, 0.065]}>
        <mesh geometry={nodes.Cube004_1.geometry} material={coloured.accWhiteToCream} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['red.002']} />
      </group>
      <group position={[-2.67, 1.312, -1.341]} scale={[0.113, 0.162, 0.04]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={coloured.accWhiteToCream} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['red.001']} />
      </group>
      <group position={[-2.67, 1.297, -1.418]} scale={[0.113, 0.147, 0.027]}>
        <mesh geometry={nodes.Cube023_1.geometry} material={coloured.accWhiteToCream} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials.redd} />
      </group>
      <group position={[-2.67, 1.345, -1.482]} scale={[0.113, 0.198, 0.031]}>
        <mesh geometry={nodes.Cube024_1.geometry} material={coloured.accWhiteToCream} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials.blue} />
      </group>
      <group position={[-2.67, 1.285, -1.566]} scale={[0.113, 0.137, 0.044]}>
        <mesh geometry={nodes.Cube025_1.geometry} material={coloured.accWhiteToCream} />
        <mesh geometry={nodes.Cube025_2.geometry} material={materials.turquip} />
      </group>
      <group position={[-2.67, 1.312, -1.641]} scale={[0.113, 0.162, 0.029]}>
        <mesh geometry={nodes.Cube027_1.geometry} material={coloured.accWhiteToCream} />
        <mesh geometry={nodes.Cube027_2.geometry} material={materials.clay_pot} />
      </group>
      <group position={[0.684, -1.2, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.122, 0.058]}>
        <mesh geometry={nodes.Cube028_1.geometry} material={materials.bread} />
        <mesh geometry={nodes.Cube028_2.geometry} material={coloured.accWhiteToCream} />
      </group>
      <mesh geometry={nodes.Cube067.geometry} material={coloured.accentSage} position={[0.781, -1.176, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.144, 0.036]} />
      <group position={[0.85, -1.19, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.131, 0.024]}>
        <mesh geometry={nodes.Cube069_1.geometry} material={materials['red.001']} />
        <mesh geometry={nodes.Cube069_2.geometry} material={coloured.accWhiteToNavy} />
      </group>
      <mesh geometry={nodes.Cube069.geometry} material={coloured.shelfAccent} position={[0.907, -1.147, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.176, 0.027]} />
      <group position={[0.982, -1.2, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.122, 0.039]}>
        <mesh geometry={nodes.Cube071_1.geometry} material={materials.clay_pot} />
        <mesh geometry={nodes.Cube071_2.geometry} material={coloured.accWhiteToSage} />
      </group>
      <mesh geometry={nodes.Cube071.geometry} material={nodes.Cube071.material} position={[1.049, -1.176, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.144, 0.025]} />
      <group position={[-0.147, -1.652, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.122, 0.058]}>
        <mesh geometry={nodes.Cube073_1.geometry} material={materials.cardboard} />
        <mesh geometry={nodes.Cube073_2.geometry} material={coloured.accWhiteToTerracotta} />
      </group>
      <group position={[-0.05, -1.628, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.144, 0.036]}>
        <mesh geometry={nodes.Cube074_1.geometry} material={materials['cardboard.001']} />
        <mesh geometry={nodes.Cube074_2.geometry} material={coloured.accWhiteToCream} />
      </group>
      <group position={[0.02, -1.642, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.131, 0.024]}>
        <mesh geometry={nodes.Cube075_1.geometry} material={materials['red.002']} />
        <mesh geometry={nodes.Cube075_2.geometry} material={coloured.accWhiteToCream} />
      </group>
      <mesh geometry={nodes.Cube075.geometry} material={materials.turquip} position={[0.076, -1.599, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.176, 0.027]} />
      <group position={[0.151, -1.652, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.122, 0.039]}>
        <mesh geometry={nodes.Cube077_1.geometry} material={coloured.accentWood} />
        <mesh geometry={nodes.Cube077_2.geometry} material={materials.white} />
      </group>
      <group position={[0.218, -1.628, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.144, 0.025]}>
        <mesh geometry={nodes.Cube078_1.geometry} material={materials.blue} />
        <mesh geometry={nodes.Cube078_2.geometry} material={coloured.accWhiteToSage} />
      </group>
      <group position={[-0.969, -1.628, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.144, 0.025]}>
        <mesh geometry={nodes.Cube079_1.geometry} material={materials.brown} />
        <mesh geometry={nodes.Cube079_2.geometry} material={coloured.accWhiteToCream} />
      </group>
      <mesh geometry={nodes.Cube079.geometry} material={materials.blue} position={[-0.912, -1.628, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.144, 0.025]} />
      <group position={[-0.595, -1.751, -2.257]} rotation={[-Math.PI / 2, 0, -1.909]} scale={[0.101, 0.144, 0.025]}>
        <mesh geometry={nodes.Cube081_1.geometry} material={materials.green} />
        <mesh geometry={nodes.Cube081_2.geometry} material={materials['white computer']} />
      </group>
      <mesh geometry={nodes.Cube081.geometry} material={materials['red.001']} position={[0.712, -1.751, -2.257]} rotation={[-Math.PI / 2, 0, -0.765]} scale={[0.101, 0.144, 0.025]} />
      <mesh geometry={nodes.Cube082.geometry} material={coloured.accentSage} position={[-0.538, -1.147, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.176, 0.027]} />
      <group position={[-0.463, -1.2, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.122, 0.039]}>
        <mesh geometry={nodes.Cube084_1.geometry} material={coloured.shelfBacking} />
        <mesh geometry={nodes.Cube084_2.geometry} material={coloured.accWhiteToNavy} />
      </group>
      <group position={[-0.396, -1.176, -2.179]} rotation={[0, -Math.PI / 2, 0]} scale={[0.101, 0.144, 0.025]}>
        <mesh geometry={nodes.Cube085_1.geometry} material={materials.clay_pot} />
        <mesh geometry={nodes.Cube085_2.geometry} material={coloured.accWhiteToSage} />
      </group>
      <group position={[-0.929, -1.176, -2.179]} rotation={[Math.PI / 2, -1.326, Math.PI / 2]} scale={[0.101, 0.144, 0.025]}>
        <mesh geometry={nodes.Cube086_1.geometry} material={materials.turquip} />
        <mesh geometry={nodes.Cube086_2.geometry} material={coloured.accWhiteToCream} />
      </group>
      <group position={[0.212, -1.298, -2.263]} rotation={[Math.PI / 2, 0, -0.466]} scale={[0.101, 0.144, 0.025]}>
        <mesh geometry={nodes.Cube087_1.geometry} material={materials.blue} />
        <mesh geometry={nodes.Cube087_2.geometry} material={coloured.accWhiteToTerracotta} />
      </group>
      <group position={[3.261, -1.63, -2.26]} scale={[0.26, 0.322, 0.231]}>
        <mesh geometry={nodes.Cube088_1.geometry} material={materials['black mouse']} />
        <mesh geometry={nodes.Cube088_2.geometry} material={coloured.foregroundCabinet} />
      </group>
      <group position={[-2.67, 0.973, 1.431]} scale={[0.113, 0.162, 0.04]}>
        <mesh geometry={nodes.Cube089_1.geometry} material={coloured.accWhiteToCream} />
        <mesh geometry={nodes.Cube089_2.geometry} material={materials['red.001']} />
      </group>
      <group position={[-2.67, 0.957, 1.353]} scale={[0.113, 0.147, 0.027]}>
        <mesh geometry={nodes.Cube091_1.geometry} material={materials.blue} />
        <mesh geometry={nodes.Cube091_2.geometry} material={coloured.accWhiteToCream} />
      </group>
      <group position={[-2.588, 0.846, 1.699]} rotation={[-Math.PI / 2, 0, -1.209]} scale={[0.084, 0.12, 0.03]}>
        <mesh geometry={nodes.Cube092_1.geometry} material={coloured.shelfBacking} />
        <mesh geometry={nodes.Cube092_2.geometry} material={coloured.accWhiteToCream} />
      </group>
      <group position={[-2.594, 0.565, 2.232]} rotation={[-Math.PI / 2, 0, -1.209]} scale={[0.084, 0.12, 0.03]}>
        <mesh geometry={nodes.Cube093_1.geometry} material={materials.blue} />
        <mesh geometry={nodes.Cube093_2.geometry} material={coloured.accWhiteToCream} />
      </group>
      <mesh geometry={nodes.Cube092.geometry} material={materials.brown} position={[-2.594, 0.626, 2.232]} rotation={[-Math.PI / 2, 0, -0.414]} scale={[0.084, 0.12, 0.03]} />
      <mesh geometry={nodes.Cube093.geometry} material={materials.blue} position={[-2.573, 1.181, -0.934]} rotation={[1.509, -0.071, 0.561]} scale={[0.113, 0.198, 0.031]} />
      <mesh geometry={nodes.Cube094.geometry} material={materials.turquip} position={[-2.701, 1.349, -0.419]} rotation={[-Math.PI / 2, 1.309, Math.PI / 2]} scale={[0.113, 0.198, 0.031]} />
      <mesh geometry={nodes.Cube095.geometry} material={materials.green} scale={[2.781, 1.95, 2.67]} />
      <mesh geometry={nodes.Cube096.geometry} material={materials['broewn riug']} position={[3.304, -2.109, -0.084]} scale={[1.829, 1.95, 1.854]} />
      <mesh geometry={nodes.Cube097.geometry} material={coloured.shelfFrameMat} position={[-0.406, 1.58, -2.722]} scale={[1.074, 0.087, 0.014]} />
      <mesh geometry={nodes.Cube098.geometry} material={coloured.shelfFrameMat} position={[-0.406, 1.405, -2.722]} scale={[1.074, 0.087, 0.014]} />
      <mesh geometry={nodes.Cube099.geometry} material={coloured.shelfFrameMat} position={[-0.406, 1.231, -2.722]} scale={[1.074, 0.087, 0.014]} />
      <mesh geometry={nodes.Cube100.geometry} material={coloured.shelfFrameMat} position={[-0.406, 1.056, -2.722]} scale={[1.074, 0.087, 0.014]} />
      <mesh geometry={nodes.Cube101.geometry} material={coloured.shelfFrameMat} position={[-0.406, 0.882, -2.722]} scale={[1.074, 0.087, 0.014]} />
      <mesh geometry={nodes.Cube102.geometry} material={materials['red.002']} scale={[2.781, 1.95, 2.67]} />
      <mesh geometry={nodes.Cube103.geometry} material={materials['Material.007']} position={[0.42, 0.856, -1.069]} scale={0.126} />
      <mesh geometry={nodes.Cylinder.geometry} material={coloured.standDark} position={[-2.377, -0.595, 0.546]} rotation={[0, -1.011, 0]} scale={0.085} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['grey metallic']} position={[3.278, -0.665, -2.587]} scale={0.083} />
      <group position={[2.144, -0.758, -2.547]} scale={0.076}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Glass.001']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Lid Metal']} />
      </group>
      <group position={[-2.065, -0.578, -2.215]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.003}>
        <mesh geometry={nodes.Mesh014.geometry} material={materials['DB_Apps&Tech_101_14']} />
        <mesh geometry={nodes.Mesh014_1.geometry} material={materials['DB_Apps&Tech_101_03']} />
        <mesh geometry={nodes.Mesh014_2.geometry} material={materials['DB_Apps&Tech_101_04']} />
        <mesh geometry={nodes.Mesh014_3.geometry} material={materials['DB_Apps&Tech_101_14.001']} />
        <mesh geometry={nodes.Mesh014_4.geometry} material={materials['DB_Apps&Tech_101_16']} />
        <mesh geometry={nodes.Mesh014_5.geometry} material={materials['DB_Apps&Tech_101_07']} />
        <mesh geometry={nodes.Mesh014_6.geometry} material={materials['DB_Apps&Tech_101_08']} />
        <mesh geometry={nodes.Mesh014_7.geometry} material={materials['DB_Apps&Tech_101_09']} />
        <mesh geometry={nodes.Mesh014_8.geometry} material={materials['DB_Apps&Tech_101_10']} />
        <mesh geometry={nodes.Mesh014_9.geometry} material={materials['DB_Apps&Tech_101_11']} />
        <mesh geometry={nodes.Mesh014_10.geometry} material={materials['DB_Apps&Tech_101_12']} />
        <mesh geometry={nodes.Mesh014_11.geometry} material={materials['DB_Apps&Tech_101_13']} />
      </group>
      <mesh geometry={nodes.headphone.geometry} material={materials['red.001']} position={[-2.001, -0.708, -1.352]} rotation={[Math.PI / 2, 1.201, -1.572]} scale={[0.036, 0.012, 0.007]} />
      <group position={[-2.574, 1.843, -2.652]} scale={-0.021}>
        <mesh geometry={nodes.Icosphere_1.geometry} material={materials.bulb} />
        <mesh geometry={nodes.Icosphere_2.geometry} material={coloured.lampShadeMat} />
      </group>
      <group position={[-2.774, 1.843, -2.497]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.017, -0.021, -0.021]}>
        <mesh geometry={nodes.Icosphere021.geometry} material={materials.bulb} />
        <mesh geometry={nodes.Icosphere021_1.geometry} material={coloured.lampShadeMat} />
      </group>
      <group position={[2.31, -0.754, -2.38]} scale={0.074}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Metal Cover']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials.Label} />
        <mesh geometry={nodes.Cylinder001_4.geometry} material={materials.Fill} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials.brown} position={[-2.684, -0.97, 1.794]} rotation={[0, 0, -Math.PI / 2]} scale={[0.98, 0.543, 0.715]} />
      <group position={[-2.149, -0.711, -0.372]} rotation={[-Math.PI, 1.566, -Math.PI]} scale={[0.315, 0.405, 0.095]}>
        <mesh geometry={nodes.Plane013_1.geometry} material={materials.moniter} />
        <mesh geometry={nodes.Plane013_2.geometry} material={materials['eye back.001']} />
        <mesh geometry={nodes.Plane013_3.geometry} material={materials['eye back.002']} />
      </group>
      <group position={[-1.387, -1.567, -1.752]} rotation={[Math.PI / 2, 0, 0]} scale={[0.143, 0.158, 0.158]}>
        <mesh geometry={nodes.Plane019.geometry} material={materials['cardboard.001']} />
        <mesh geometry={nodes.Plane019_1.geometry} material={coloured.accWhiteToCream} />
        <mesh geometry={nodes.Plane019_2.geometry} material={materials.b_pvc} />
        <mesh geometry={nodes.Plane019_3.geometry} material={materials.wire_029029029} />
        <mesh geometry={nodes.Plane019_4.geometry} material={materials['file.001']} />
        <mesh geometry={nodes.Plane019_5.geometry} material={materials.filee} />
        <mesh geometry={nodes.Plane019_6.geometry} material={materials.file} />
      </group>
      <mesh geometry={nodes.Plane152.geometry} material={materials['rug f']} position={[2.312, -0.835, -2.343]} scale={[0.328, 0.148, 0.148]} />
      <group position={[0.049, -0.863, -2.359]} scale={[1.119, 0.148, 0.148]}>
        <mesh geometry={nodes.Plane154_1.geometry} material={materials.b_pvc} />
        <mesh geometry={nodes.Plane154_2.geometry} material={materials['new ruug']} />
      </group>
      {/* <group position={[1.759, -1.561, -1.023]} rotation={[0, 0.144, 0]} scale={[0.399, 0.148, 0.149]}>
        <mesh geometry={nodes.Plane155_1.geometry} material={materials.rug} />
        <mesh geometry={nodes.Plane155_2.geometry} material={materials.b_pvc} />
      </group> */}
      <group position={[-2.819, 0.539, 2.297]} scale={[0.399, 0.148, 0.149]}>
        <mesh geometry={nodes.Plane156_1.geometry} material={materials['rug.001']} />
        <mesh geometry={nodes.Plane156_2.geometry} material={materials.b_pvc} />
      </group>
      <mesh geometry={nodes.Plane156.geometry} material={materials.rug} position={[-2.819, 0.814, 1.62]} scale={[0.399, 0.148, 0.149]} />
      <mesh geometry={nodes.Plane157.geometry} material={materials.rugg} position={[-2.785, 1.151, -0.418]} scale={[0.399, 0.148, 0.728]} />
      <group position={[3.26, -1.205, -2.263]} scale={0.069}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials.b_pvc} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials.metallic_k} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={coloured.standOlive} />
      </group>
      <mesh geometry={nodes.speaker.geometry} material={materials['eye back']} position={[-2.662, -0.459, 0.678]} scale={[0.118, 0.262, 0.148]} />
      <mesh geometry={nodes.speaker001.geometry} material={materials['eye back']} position={[-2.662, -0.459, -1.372]} scale={[0.118, 0.262, 0.148]} />
      <InteractiveObject id="LAMP">
        <group position={[-1.998, -0.224, 0.821]} scale={-0.047}>
          <mesh geometry={nodes.Sphere005_1.geometry} material={coloured.floorLampShade} />
          <mesh geometry={nodes.Sphere005_2.geometry} material={coloured.lampStand} />
        </group>
      </InteractiveObject>
      <mesh geometry={nodes.Text001.geometry} material={materials.b_pvc} position={[-2.082, -1.33, -2.02]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.048} />
      <mesh geometry={nodes.Text002.geometry} material={materials.b_pvc} position={[-2.082, -1.699, -2.069]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.164} />
      <mesh geometry={nodes.uploads_files_1979612_cardboar_box_pack.geometry} material={materials['cardboard.001']} position={[2.695, -1.231, 1.905]} rotation={[Math.PI / 2, 0.11, 0]} scale={0.007} />
      <mesh geometry={nodes.uploads_files_1979612_cardboar_box_pack001.geometry} material={materials['cardboard.001']} position={[1.879, -0.274, 1.976]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
      <mesh geometry={nodes.uploads_files_1979612_cardboar_box_pack002.geometry} material={materials['cardboard.002']} position={[2.734, -1.785, 2.212]} rotation={[Math.PI / 2, 0, 0]} scale={[0.006, 0.006, 0.007]} />
      <mesh geometry={nodes.uploads_files_1979612_cardboar_box_pack004.geometry} material={materials['cardboard.002']} position={[2.734, -1.785, 1.634]} rotation={[Math.PI / 2, 0, 0]} scale={[0.006, 0.006, 0.007]} />
      <mesh geometry={nodes.uploads_files_1979612_cardboar_box_pack005.geometry} material={materials.cardboard} position={[2.69, -1.442, 1.958]} rotation={[Math.PI / 2, 0, 0]} scale={[0.003, 0.004, 0.003]} />
    </group>
  )
}

useGLTF.preload('/models/bedroom.glb')
